### ISSUE TITLE
使用Vite打包，日期选择器组件出错

### ISSUE THREAD

**Issue by pwpow** [wxad/adui#2]
背景：
https://github.com/gpbl/react-day-picker/issues/1194

点击前：
日期组件正常显示
![image](https://user-images.githubusercontent.com/35388969/124085235-65980f80-da82-11eb-9bde-e72677275eab.png)

点击后：
页面白屏，报错信息如下
![image](https://user-images.githubusercontent.com/35388969/124085323-7fd1ed80-da82-11eb-992e-d4d756bc2647.png)

**Comment by jiangyijie27** [comment]
感谢 @pwpow，我持续跟进 react day picker

**Comment by Miantang** [comment]
day-picker-react

**Comment by jiangyijie27** [comment]
@pwpow @Miantang

**Comment by jiangyijie27** [comment]
@Miantang @pwpow 

已使用 issue 中的临时解决方案修复。

adui@2.5.0
