### ISSUE TITLE
Table组件的onSelectChange事件建议支持传递当前行的状态和数据

### ISSUE THREAD

**Issue by fengxianqi** [wxad/adui#21]
背景：
table组件无法直接获取当前操作的行，如选中或取消选中，当前行的数据等，希望支持。

目前table组件只支持`onSelectChange `事件，该事件只能全量获取所有已选中的keys，不能获取当前操作的行：
<img width="1458" alt="image" src="https://user-images.githubusercontent.com/15716381/171359681-c15a5f89-8eb5-43fd-82e5-3316bdbf645e.png">

参考[Tdesign](https://tdesign.woa.com/react/components/table?tab=api)，支持更多的参数：
<img width="1649" alt="image" src="https://user-images.githubusercontent.com/15716381/171361238-1d554821-3bb3-42b6-a166-2772f242c5f9.png">

或者参考[antd](https://ant.design/components/table-cn/#rowSelection)，通过`onSelect`事件，它可以帮助用户获取当前选中的行：
<img width="2415" alt="image" src="https://user-images.githubusercontent.com/15716381/171360246-41b2dab8-bc87-4492-8d00-16010ce35d36.png">

**Comment by jiangyijie27** [comment]
@fengxianqi adui@2.35.0

新增第二个参数 `options`，此参数是可选的 —— 全选时为 `undefined`。其中：
1. `selected` 表示当前行操作是选中还是取消选中；
2. `selectedRows` 表示当前已选中的行；
3. `currentRowKey` 表示当前操作行的 key；
4. `currentRow` 表示当前操作行的数据。

```ts
onSelectChange?:
  | ((
      keys: Array<React.ReactText>,
      options?: {
        selected: boolean
        selectedRows: T[]
        currentRowKey: React.ReactText
        currentRow: T
      }
    ) => void)
  | null
```
