### ISSUE TITLE
表格Table组件 筛选 能否支持多选

### ISSUE THREAD

**Issue by pwpow** [wxad/adui#25]
目前表格Table组件 筛选能力 仅支持单选，能否支持多选
![image](https://user-images.githubusercontent.com/35388969/173792754-365316ae-e4fe-4be9-8f8f-08ad3cbe5f82.png)

**Comment by jiangyijie27** [comment]
@pwpow `filterMultiple: true`

**Comment by pwpow** [comment]
> @pwpow `filterMultiple: true`
> 
> https://codesandbox.io/s/kind-black-pwd97e?file=/index.js:524-556

收到，感谢~

不过发现多选时，右侧icon没有高亮~
![image](https://user-images.githubusercontent.com/35388969/177076979-98059170-5501-4598-8f0f-0b040de349bc.png)
