### ISSUE TITLE
表格组件能否支持列同时使用筛选和排序

### ISSUE THREAD

**Issue by pwpow** [wxad/adui#27]
目前表格组件不支持同时使用筛选和排序功能：
<img width="774" alt="企业微信截图_16566481412635" src="https://user-images.githubusercontent.com/35388969/176821399-389c7a59-7ff5-4fd2-b679-095fb2e5a7e9.png">

期望能支持该能力~
![image](https://user-images.githubusercontent.com/35388969/176821436-417f791d-45cf-435d-b7b6-e63dc86dd188.png)

![image](https://user-images.githubusercontent.com/35388969/176821541-bf57dac4-5c98-43a2-9eef-05faf89e1eb1.png)

**Comment by jiangyijie27** [comment]
adui@2.37.0 https://codesandbox.io/s/vigilant-matsumoto-2fr465?file=/index.js
