### ISSUE TITLE
TreeSelect 数据中如果有重复ID展示会出错

### ISSUE THREAD

**Issue by Miantang** [wxad/adui#3]
<img width="1008" alt="11" src="https://user-images.githubusercontent.com/3156907/127090962-2553acfd-c531-488a-90c6-824ffdb68987.png">
如果填入数据存在重复ID，在对应展开项的地方，进行滚动，会不停地渲染新的Item

https://codesandbox.io/s/cool-tdd-gh7sf

**Comment by jiangyijie27** [comment]
这个倒是已知的，不过不算是 bug 吧，prop 要避免这种情况。

如果说有意要重复的话，比如企业微信的组织架构，相同的人在不同的树里都会出现，可以用

<TreeSelect sameValueEnabled />

https://codesandbox.io/s/er2cs?file=/index.js:2053-2069

**Comment by Miantang** [comment]
> 这个倒是已知的，不过不算是 bug 吧，prop 要避免这种情况。
> 
> 如果说有意要重复的话，比如企业微信的组织架构，相同的人在不同的树里都会出现，可以用
> 
> https://codesandbox.io/s/er2cs?file=/index.js:2053-2069

2023.03.01 update:
这个方案，不太完美

这个问题是由于下拉框使用虚拟列表，而虚拟列表滚动的时候会重复添加重复key

新增配置 virtual={false} 可以解决（性能有所损耗）
