### ISSUE TITLE
表格组件Column algin 配置仅对表头生效，未对表格数据生效

### ISSUE THREAD

**Issue by pwpow** [wxad/adui#30]
升级adui组件库版本后，发现表格对齐表现与原来不一致
期望对column设置algin对表头和数据同时生效

![image](https://user-images.githubusercontent.com/35388969/178430082-993caeb0-d3e5-4edc-ae7e-8a0123bc36b4.png)

**Comment by jiangyijie27** [comment]
adui@2.37.1
