### ISSUE TITLE
TreeSelect 组件父节点 disabled 状态下选中子节点父节点没有显示禁用态下的选中状态，看起来像是没有选中

### ISSUE THREAD

**Issue by zhengpq** [wxad/adui#34]
<img width="502" alt="image" src="https://user-images.githubusercontent.com/24761793/185284217-540d41ce-974a-4654-b23a-41134ebd968d.png">
<img width="643" alt="image" src="https://user-images.githubusercontent.com/24761793/185284244-de7bbcf9-d88f-4f1f-b960-6cc664251f19.png">

代码链接实例

https://codesandbox.io/s/objective-river-4rhrqm?file=/index.js

**Comment by jiangyijie27** [comment]
问题记录：

**Comment by jiangyijie27** [comment]
问题记录：

原需求可能是在全 disabled 情况下必须展开父级才可看到底下的状态，
在展开以前，用户无法感知到自己已进行选择。

确实是个体验问题。

然而 antd 的组件设计每个 node 是独立的，父级在 disabled 的情况不再包含子级的选中状态。
在 antd 的角度 it's probably a feature, not a bug.
相关讨论：https://github.com/ant-design/ant-design/issues/34747

解决方法是用 CSS 强行 hack，无奈。
参照这层的做法： https://github.com/ant-design/ant-design/issues/34747#issuecomment-1192446474

1. 无法再是用提供的 `disabled` Prop，因此在这种情况下**全部**替换为覆盖类 `className: "disable-manually"`
2. 样式如下，大致就是从文字、背景、勾选全方位 hack default style，`!important` 也是必要的：

```
.adui-tree-select-dropdown-hidden {
  display: block!important;
}
.disable-manually {
  color: var(--transparent-gray-700);
}
.disable-manually:hover {
  background: transparent!important;
}
.disable-manually::after {
  content: "";
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  z-index: 2;
  cursor: not-allowed;
}
.disable-manually .adui-tree-select-tree-checkbox {
  background-color: rgba(0,0,0,.03)!important;
  box-shadow: 0 0 0 1px rgb(0 0 0 / 8%)!important;
}
.disable-manually .adui-tree-select-tree-checkbox * {
  fill: var(--gray-600)!important;
}
```
