### ISSUE TITLE
TableColumn width 的问题

### ISSUE THREAD

**Issue by HelKyle** [wxad/adui#6]
## 问题描述   
当前 TableColumn 的 width 参数会传给 td, th 的 maxWidth。

```js
maxWidth: resizedCol ? resizedCol.value : width || ""
```

在 table 列动会跟着筛选项目变更的场景下，使用起来会产生一些奇怪的问题，比如如果都是固定宽度的列，可能出现撑不满一行；比如只有一列没有传 width，会自动拉伸这一列，很大面积空白，显得非常突兀。

**没撑满**
![image](https://user-images.githubusercontent.com/9882649/135222223-0bf1ac3a-e9ea-442a-a230-1c3626d33634.png)

**大面积空白**
![image](https://user-images.githubusercontent.com/9882649/135222358-740a4c71-69ea-4efe-b844-65f040f6bb85.png)

**期望效果**
![image](https://user-images.githubusercontent.com/9882649/135222807-6c32fae6-8141-4d37-abca-746a98fdb873.png)

希望可以支持固定一列，剩余列按照各自比例拉伸占满一行。

## 方案   
`TableColumn` 增加一个 `baseWidth` 的参数，支持用户传入列的默认 `flex-grow` 但是不影响 `maxWidth`。

**Comment by jiangyijie27** [comment]
https://codesandbox.io/s/sad-kalam-4wof4?file=/src/App.tsx

adui@2.15.0 grow Prop featured
